= CalConnect Standard: Lightweight document -- Document metamodel

This work item belongs to TC VCARD.

image:https://travis-ci.com/CalConnect/csd-lightweight-doc.svg?branch=master["Build Status", link="https://travis-ci.com/calconnect/csd-lightweight-doc"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-lightweight-doc/[CC/ISO: Lightweight document -- Document metamodel (HTML)]

== Publication sequence

This document is published in two flavours from the same sources:

1. *CC 36010* — the CalConnect standard, published by CalConnect
   (this repository, `sources/cc-36010.adoc`).
2. *ISO 36010* — the fast-track Draft International Standard copy for
   ISO/TC 154 (`sources/iso-36010.adoc`), submitted after CalConnect
   publication, per the ISO fast-track procedure.

Both flavours compile from the shared section sources; flavour-specific
content is limited to the foreword and document attributes.

== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-lightweight-doc/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open cc-*.html
----

