
== Scope

This document provides a reference lightweight document model called
_BasicDocument_ for generic documents, intended as an
interoperable basis that allows systems to interchange
generic document content while preserving semantics.

This document model can be directly utilized to represent
interchangeable document content, or adopted, superseded or internalized
by document representation models and formats in order
to represent document content in other forms.

The application of the reference model to particular classes of
documents, such as business documents exchanged in commerce, is
illustrated in Annex E.

The modelling of bibliographies and citations is part of the reference model,
but is the subject of a separate document, <<relaton>>,
and are hence not described in detail in this document.

The following aspects are excluded from scope:

* Specialization and profiling of this model to specialized classes of documents;

* Implementation of the reference model and serialization formats;

* Mapping of the reference model to output formats; and

* Markup schemes and syntaxes that enable creation of documents that fit the reference model.
